name: UPLOAD TYPES

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 19.x
          cache: "yarn"
      - name: Install yarn
        run: yarn install
      - name: Prisma
        run: |
          yarn prisma generate
      - name: Checkout types repo
        uses: actions/checkout@v4
        with:
          repository: School-Mate/School-Mate-Types
          path: types
          token: ${{secrets.OMBE_TOKEN}}
      - name: Upload types
        run: |
          rm -rf ~/types/src/prisma/*
          cp -r ~/School-Mate-Backend/School-Mate-Backend/node_modules/@prisma/client ~/types/src/prisma
          cd ~/types
          git add . 
          git commit -m "feat: update types"
          git push https://${{secrets.OMBE_TOKEN}}@github.com/School-Mate/School-Mate-Types.git
      